import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import { App } from "@/modules/app";
import { Header } from "@/modules/widgetes";
import { AppProvider } from "@/modules/app/providers/AppProvider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className="scrollbar-hide"
            suppressHydrationWarning
            data-theme="system"
        >
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background`}
            >
                <AppProvider>
                    <>
                        <div className="fixed top-0 left-0 w-full bg-background z-50 h-[46px]">
                            <Header />
                        </div>
                        <div className="h-calc(100vh-46px) w-full">
                            {children}
                        </div>
                    </>
                </AppProvider>
            </body>
        </html>
    );
}
